# Generated by Django 5.1.6 on 2025-02-26 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_heading_post_alter_postanalytics_post_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postview',
            old_name='ip_adress',
            new_name='ip_address',
        ),
    ]
